replicas: 1
cpu:
  requests: "25m"
  limits: "8000m"
memory:
  requests: "64Mi"
  limits: "16Gi"
serviceType: ClusterIP
image:
  Name: lsheiba/tensorflow-ls-devel
  Tag: latest
persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 1Gi
